### ISSUE TITLE
How do I build your plugin?

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [mongodb/vault-plugin-secrets-mongodbatlas#23]
Hi,
since we are being pressured to migrate off mlab I'm in dire need to use your plugin right now. Unfortunately the readme is wrong, also every attempt at building your master fails. Do you have a proper method of building this plugin? I don't really understand why you're pressuring people off mLab while you can't provide similar features.

**Comment by themantissa** [comment]
@heprotecbuthealsoattac as noted in the last issue we have this work now in Vault, the 1.4Beta1 release.  If you run into any issues please feel free to reach out directly to me.   Thank you!
