### ISSUE TITLE
Hashicorp 404 in Readme

### ISSUE THREAD

**Issue by esteininger** [mongodb/vault-plugin-secrets-mongodbatlas#31]
Both Hashicorp URLs:
- https://www.vaultproject.io/docs/secrets/mongodbatlas
- https://www.vaultproject.io/api-docs/secret/mongodbatlas/
Result in 404's

**Comment by themantissa** [comment]
Hi @esteininger they should work (if we were given the right links) as of tomorrow (4/7) when Vault 1.4 GAs.  This repo will also go readonly soon and you can follow in the new home for this work: https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas
